version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  deploy:
    # environment:
    #   AWS_REGION: eu-west-2
    steps:
      - checkout
      - aws-s3/sync:
          from: . # From where???
          to: 's3://www.gregoriofumagalli.com/'
          # arguments: |
          #   --acl public-read \
          #   --cache-control "max-age=86400"
workflows:
  version: 2.1
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main