version: 2.1
jobs:
  # Removed the "test" job
workflows:
  version: 2.1
  build:
    jobs:
      # Removed the "test" job reference
      # Only builds the code on the main and develop branches
      - build:
          filters:
            branches:
              only:
                - main
                - develop